feeds/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^(?P<feed_id>[0-9]+)/$', views.detail, name='detail'),
]

reader/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.read, name='read'),
]

rssreadability/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^feeds/', include('feeds.urls', namespace='feeds')),
    url(r'^reader/', include('reader.urls', namespace='reader')),
    url(r'^admin/', include(admin.site.urls)),
]

feeds/models.py
from django.db import models

class Feed(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    def __str__(self):
        return self.name

reader/models.py
from django.db import models

# Create your models here.

feeds/views.py
from django.shortcuts import get_object_or_404,render
from .models import Feed
from feedparser import parse

def index(request):
    feed_list = Feed.objects.all()
    context = {'feed_list': feed_list}
    return render(request, 'feeds/index.html', context) 

def detail(request, feed_id):
    feed = get_object_or_404(Feed, pk=feed_id)
    d = parse(feed.url)
    context = {
            'feed': d.feed,
            'entry_list': d.entries,
    }
    return render(request, 'feeds/detail.html', context)

reader/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.http import HttpResponseNotFound

from readability.readability import Document
from urllib.request import urlopen
from lxml import html

@require_http_methods(["GET", "POST"])
def read(request):
    if request.POST:
        url = request.POST['url']
    elif request.GET:
        url = request.GET['url']
    else:
        return HttpResponseNotFound()
    rawhtml = urlopen(url).read()
    document = Document(rawhtml, negative_keywords="reactie")
    article = html.fromstring(document.summary(html_partial=True))
    #article.rewrite_links(lambda url: url,resolve_base_href=True )
    for link in article.iterlinks():
        if link[0].tag == 'a':
            link[0].set('href','/reader/?url='+link[2])
    context = {
            'title': document.short_title(),
            'aside': url,
            'content': html.tostring(article),
    }
    return render(request, 'reader/read.html', context)

feeds/templates/feeds/detail.html
<p>{{ feed.title }}</p>
{% if entry_list %}
  <ul>
  {% for entry in entry_list %}	
    <li>
      <p>{{ entry.title }}</p>
      <p>{{ entry.description }}</p>
      <form action="{% url 'reader:read' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="url" value="{{ entry.link }}" />
          <input type="submit" value="Read more" />
      </form>
    </li>
  {% endfor %}
  </ul>
{% endif %}

feeds/templates/feeds/index.html
{% if feed_list %}
  <ul>
  {% for feed in feed_list %}
    <li><a href="{% url 'feeds:detail' feed.id %}">{{ feed.name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No feeds</p>
{% endif %}

reader/templates/reader/read.html
{% extends "base.html" %}

{% block header %}
  <h1>{{ title }}</h1>
  <aside>{{ url }}<aside>
{% endblock %}

{% block content %}
  {{ content|safe }}
{% endblock %}

rssreadability/templates/base.html
{% loadstatic %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="style.css" />
  <title>{% block title %}RSS Readability{% endblock %}</title>
</head>

<body>
  <header>
    {% block header %}{% endblock %}
  </header>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
</body>
</html>